# Generated by Django 4.2.23 on 2025-08-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league.division'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'division', 'year')},
        ),
        migrations.RemoveField(
            model_name='team',
            name='type',
        ),
    ]
