# Generated by Django 4.2.23 on 2025-08-26 14:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_team_division_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1B', '1st Base'), ('2B', '2nd Base'), ('3B', '3rd Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('P', 'Pitcher'), ('C', 'Catcher')], max_length=24),
        ),
    ]
