# Generated by Django 4.2.23 on 2025-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_remove_player_position_player_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('1B', '1st Base'), ('2B', '2nd Base'), ('3B', '3rd Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('P', 'Pitcher'), ('C', 'Catcher')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='positions',
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='players', to='league.position'),
        ),
    ]
