# Generated by Django 4.2.23 on 2025-08-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_position_remove_player_positions_player_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_allstar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_showcase',
            field=models.BooleanField(default=False),
        ),
    ]
