# Generated by Django 4.2.23 on 2025-09-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_player_is_allstar_player_is_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
