# Generated by Django 4.2.23 on 2025-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_player_latitude_player_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='full_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='in_district',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
