# Generated by Django 4.2.23 on 2025-11-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_player_full_address_player_in_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='full_address',
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
