# Generated by Django 4.2.23 on 2026-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_remove_player_full_address_alter_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='district_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='in_district',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('first_name', 'last_name', 'date_of_birth', 'address_line_1')},
        ),
    ]
