# Generated by Django 4.2.23 on 2026-02-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_player_district_checked_at_alter_player_in_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coach_request',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='interested_showcase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='residency_same',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='teammate_request',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
