# Generated by Django 4.2.23 on 2026-03-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_player_coach_request_player_interested_showcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
