# Generated by Django 4.2.23 on 2026-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_remove_evaluation_catcher_throwing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
