# Generated by Django 4.2.23 on 2026-03-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.division')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='league.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_selections', to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_selections', to='league.team')),
            ],
            options={
                'unique_together': {('draft', 'player')},
            },
        ),
    ]
