# Generated by Django 4.2.23 on 2026-03-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_draftselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='drafts', to='league.team'),
        ),
    ]
