# Generated by Django 4.2.23 on 2026-03-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_draft_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
