# Generated by Django 4.2.23 on 2026-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_team_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='catcher_tier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='pitcher_tier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='tier',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
