# Generated by Django 4.2.23 on 2026-03-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_player_catcher_tier_player_pitcher_tier_player_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='catcher_tier',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pitcher_tier',
        ),
    ]
