# Generated by Django 4.2.23 on 2026-03-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_remove_player_catcher_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='teams',
        ),
        migrations.AddField(
            model_name='draft',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='league.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
