# Generated by Django 4.2.23 on 2026-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_remove_draft_teams_draft_division_draft_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='selected_teams',
            field=models.ManyToManyField(blank=True, related_name='drafts', to='league.team'),
        ),
    ]
