# Generated by Django 4.2.23 on 2026-03-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_draft_selected_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='assistant_coach',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
