# Generated by Django 4.2.23 on 2026-03-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_team_assistant_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='jersey_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='jersey_color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
